#!/bin/bash
# 一键安装：在桌面生成「HTML 管理器.app」启动器
# 用法：cd 到本仓库目录，运行 ./install.sh
set -e

REPO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SERVER="$REPO_DIR/server.py"
ICON="$REPO_DIR/assets/AppIcon.icns"

if [[ ! -f "$SERVER" ]]; then
  echo "❌ 找不到 server.py，请确认在本仓库目录下运行" >&2
  exit 1
fi
if [[ ! -f "$ICON" ]]; then
  echo "❌ 找不到 assets/AppIcon.icns" >&2
  exit 1
fi

APP_NAME="${APP_NAME:-HTML 管理器.app}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/Desktop}"
APP="$INSTALL_DIR/$APP_NAME"

echo "▶ 安装到：$APP"

mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$ICON" "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>HTML 管理器</string>
    <key>CFBundleDisplayName</key>
    <string>HTML 管理器</string>
    <key>CFBundleIdentifier</key>
    <string>com.html-manager.launcher</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>10.14</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

# launcher 脚本（嵌入用户当前的 repo 绝对路径）
cat > "$APP/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
# Auto-generated by install.sh
SERVER="$SERVER"
URL="http://localhost:8765"

if curl -s -o /dev/null -w "%{http_code}" "\$URL/" 2>/dev/null | grep -q 200; then
  open "\$URL"
  exit 0
fi

nohup /usr/bin/python3 "\$SERVER" --no-open > /tmp/html-manager.log 2>&1 &
disown
sleep 1.2
open "\$URL"
exit 0
LAUNCHER

chmod +x "$APP/Contents/MacOS/launcher"
touch "$APP"

echo "✅ 安装完成"
echo ""
echo "  应用位置：$APP"
echo "  服务脚本：$SERVER"
echo "  数据存储：$HOME/.html-manager/"
echo ""
echo "  双击桌面图标即可启动。"
echo "  首次启动若提示「无法验证开发者」，请到「系统设置 → 隐私与安全性」点「仍要打开」。"
